# Generated by Django 4.1.3 on 2023-01-08 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUser', '0002_alter_perfil_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='sitio_web',
            field=models.SlugField(max_length=40),
        ),
    ]
