# Generated by Django 4.1.3 on 2023-01-08 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppUser', '0005_mensajes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensajes',
            old_name='estado',
            new_name='leido',
        ),
    ]
